# Generated by Django 4.1.7 on 2023-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_quizcategory_quesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
