# Generated by Django 4.1.7 on 2023-08-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_alter_quizcategory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcategory',
            name='detail',
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(blank=True, default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.ForeignKey(blank=True, default='Python', null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quizcategory'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(blank=True, default='Python', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(blank=True, default='Python', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(blank=True, default='Python', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op4',
            field=models.CharField(blank=True, default='Python', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.TextField(blank=True, default='Python', max_length=200, null=True),
        ),
    ]
