# Generated by Django 4.1.7 on 2023-08-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_remove_quizcategory_detail_alter_quesmodel_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Quiz.quizcategory'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.TextField(default='', max_length=200),
        ),
    ]
