# Generated by Django 4.1.7 on 2023-08-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_quesmodel_ans_alter_quesmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='', max_length=200),
        ),
    ]
